module.exports = {
	BASE_URL: "http://localhost:8000",
	REGISTER: "/api/user/register/",
	LOGIN: "/api/user/login/",
	USER: "/api/user/me/",
	USER_UPDATE: "/api/user/update/",
	USERS_ALL: "/api/user/all",
	HOME: "/api/user/home/",
	PROFILE: "/api/user/profile/",
	RANDOM: "/api/feed/random/",
	CREATE_FEED: "/api/feed/create/",
	DELETE_FEED: "/api/feed/delete",
	LIKE: "/api/feed/like/",
	FETCH_COMMENTS: "/api/feed/comments/",
	COMMENT: "/api/feed/comment/",
	FOLLOW: "/api/connection/create/",
	UNFOLLOW: "/api/connection/unfollow/",
	CONVOS: "/api/chat/convos/",
	GET_CONVO: "/api/chat/get_convo/",
};
